all:
  hosts:
    LAN:
  children:
    webservers:
      hosts:
         ip_address:
#        bar.example.com:
#    dbservers:
#      hosts:
#        one.example.com:
#        two.example.com:
#        three.example.com:
