---
- hosts: 10.0.2.15
  remote_user: user
  vars:
    project_path: /opt/test/mern-auth

  tasks:
  - name: Clear Workspace
    shell: rm -rf /opt/test/mern-auth
  - name: Git Clone Source Code
    shell: git clone https://github.com/rishipr/mern-auth.git
    args:
      creates: foobar
      chdir: /opt/test
  - name: NPM INIT
    shell: npm init -y
    args:
      creates: dir for app
      chdir: /opt/test/mern-auth
  - name: NPM Install package.json Dependencies
    npm:
      path: /opt/test/mern-auth
  - name: NPM Install & NPM Node.js Install
    npm:
      path: /opt/test/mern-auth/client
  - name:
    npm:
      name: nodemon
      path: /opt/test/mern-auth
  - name: Remove old config files
    shell: rm -f /opt/test/mern-auth/config/keys.js
  - name: cd into config directory & Copy key.js into config directory
    copy:
      src: /home/user/ansible/mern-auth/keys.js
      dest: /opt/test/mern-auth/config/keys.js
      owner: user
      group: user
      mode: '0644'
  - name: Copy Start Script
    copy:
      src: /home/user/ansible/mern-auth/services_start.sh
      dest: /opt/test/mern-auth/services_start.sh
      owner: user
      group: user
      mode: '0644'
  - name: CHMOD Start Script
    shell: chmod +x /opt/test/mern-auth/services_start.sh
  - name: Start backend Services
    command: nohup ./services_start.sh  0<&- &>/dev/null &
    async: 45
    poll: 0
    args:
      chdir: /opt/test/mern-auth
  - name: Copy API Checker
    copy:
      src: /home/user/ansible/mern-auth/curl.sh
      dest: /opt/test/mern-auth/curl.sh
      owner: user
      group: user
      mode: '0664'
  - name: CHMOD API Check Script
    shell: chmod +x /opt/test/mern-auth/curl.sh
  - name: Run API Checker
    shell: nohup /opt/test/mern-auth/curl.sh 0<&- &>/dev/null &
    async: 45
    poll: 0
